### ISSUE TITLE
Deploy Jenkins on Aliyun Kubernetes with Persistent Volume

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/kubernetes-playground#16]

**Comment by xuyuji9000** [comment]
~~Prepare PVC~~  PVC not needed now, letting helm take over the dynamic assignment

``` yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-efficiency-shanghai-e
  resources:
    requests:
      storage: 20Gi
```
