### ISSUE TITLE
Protect Jenkins with https

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/kubernetes-playground#17]
``` bash
PFX_FILE=
openssl pkcs12 -in ${PFX_FILE} -nocerts -nodes | sed -ne '/-BEGIN PRIVATE KEY-/,/-END PRIVATE KEY-/p' > clientcert.key
openssl pkcs12 -in ${PFX_FILE} -clcerts -nokeys | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >  clientcert.cer
openssl pkcs12 -in ${PFX_FILE} -cacerts -nokeys -chain | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >  cacerts.cer
```

**Comment by xuyuji9000** [comment]
- Create secret

``` bash
kubectl create secret tls yogiman.cn \
--key ./clientcert.key \
--cert ./fullchain1.pem
```

**Comment by xuyuji9000** [comment]
Upgrade Jenkins 

``` yaml
# values.yaml
master:
  ingress:
    enabled: true
    hostName: jenkins.yogiman.cn
    tls:
    - secretName: yogiman.cn
       hosts:
       - jenkins.yogiman.cn         
  serviceType: ClusterIP
persistence:
  enabled: true
  existingClaim: jenkins
```

Upgrade Jenkins 

``` bash
helm upgrade -f ./values.yaml jenkins stable/jenkins
```
