### ISSUE TITLE
Add Kubernetes jenkins executor

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/kubernetes-playground#19]
meeting error

```
Waiting for next available executor
```

during building on Jenkins

**Comment by xuyuji9000** [comment]
The Jenkins setup should be inside it's own namespace

- Get release configuration: `helm get values jenkins`

- Value:

``` yaml
# values.yaml
namespaceOverride: jenkins
master:
  ingress:
    enabled: true
    hostName: jenkins.yogiman.cn
    tls:
    - hosts:
      - jenkins.yogiman.cn
      secretName: yogiman.cn
  serviceType: ClusterIP
persistence:
  enabled: true
  existingClaim: jenkins
```

- Upgrade with values: `helm upgrade -f ./values.yaml jenkins stable/jenkins`
